wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: Convolutional Autoencoder
dataset:
  desc: null
  value: FMA
epochs:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.15.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701818131.263113
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.9.0
      5: 0.15.9
      8:
      - 3
      - 5
